// * This interfaces are generated by https://jvilk.com/MakeTypes/

export interface Sunglass {
  UPC: string;
  name: string;
  price: SunglassPrice;
  availability: SunglassAvailability;
  variants?: (SunglassVariantsEntity | null)[] | null;
}

export interface SunglassPrice {
  current: SunglassCurrent;
  currency: string;
}

export interface SunglassCurrent {
  value: number;
}

export interface SunglassAvailability {
  stock: number;
}

export interface SunglassVariantsEntity {
  UPC: string;
  name: string;
  price: SunglassPrice;
  availability: SunglassAvailability;
}
